### ISSUE TITLE
Diff test to make sure all changes on top of upstream are in place before merging a PR

### ISSUE THREAD

**Issue by muvaf** [upbound/crossplane#52]
### What problem are you facing?

Humans may miss to have the Upbound-specific changes in place or the diff commits may not be up-to-date.

### How could Crossplane help solve your problem?

@hasheddan suggested that we can have a required test that would be updated by each Upbound-specific PR together with the change they're making so that authors can make sure the change ends up in releases.

Context from Slack https://upboundio.slack.com/archives/C01PK1SMYNN/p1659916654410789

**Comment by jbw976** [comment]
It would be wise to do a bit of research to understand some patterns in the ecosystem/industry for how this case is generally approached (maintaining a long term fork with downstream specific changes that need to be preserved).
